# Writes Version.h with CLOUDMUS_VERSION, taken from `git describe --tags`:
# "0.2.0" on a release tag "v0.2.0", "0.2.0-5-g1a2b3c4" five commits after
# it, with "-dirty" for uncommitted changes — so a version copied from the
# About dialog pins down the exact build. Without any tag yet it's the
# base version from project() plus the commit ("0.1.0+g1a2b3c4[.dirty]"),
# and just the base version when git isn't available (a source tarball).
#
# Run as a script on every build (see CMakeLists.txt's cloudmus_version
# target); only rewrites the header when the string actually changed, so
# an unchanged version doesn't trigger a recompile.
#
# Inputs: BASE (version), SRC (repo root), OUT (header path).

set(version "${BASE}")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} describe --tags --dirty --match "v[0-9]*"
        WORKING_DIRECTORY ${SRC} OUTPUT_VARIABLE described OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE describeResult ERROR_QUIET)
    if(describeResult EQUAL 0 AND NOT described STREQUAL "")
        string(REGEX REPLACE "^v" "" version "${described}")
    else()
        # No release tag yet: base version + commit.
        execute_process(COMMAND ${GIT_EXECUTABLE} describe --always --dirty=.dirty
            WORKING_DIRECTORY ${SRC} OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE commitResult ERROR_QUIET)
        if(commitResult EQUAL 0 AND NOT commit STREQUAL "")
            set(version "${BASE}+g${commit}")
        endif()
    endif()
endif()

set(content "#pragma once\n\n// Generated by cmake/Version.cmake — do not edit.\n#define CLOUDMUS_VERSION \"${version}\"\n")
if(EXISTS ${OUT})
    file(READ ${OUT} existing)
endif()
if(NOT "${existing}" STREQUAL "${content}")
    file(WRITE ${OUT} "${content}")
endif()
