#!/usr/bin/env python3
"""Generates per-language protocol stubs from protocol/schema/*.yaml +
protocol/methods.yaml. See protocol/README.md.

Usage:
    python protocol/codegen/generate.py --lang python
    python protocol/codegen/generate.py --lang cpp
    python protocol/codegen/generate.py --lang python cpp   # both
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import jinja2

import cpprender
import pyrender
import schema_ir

CODEGEN_DIR = Path(__file__).resolve().parent
PROTOCOL_DIR = CODEGEN_DIR.parent
REPO_ROOT = PROTOCOL_DIR.parent

PYTHON_OUT = REPO_ROOT / "backends" / "py-rpc-common" / "rpc_common" / "generated"
CPP_OUT = REPO_ROOT / "fronts" / "qt" / "generated"


def _env(lang: str) -> jinja2.Environment:
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(CODEGEN_DIR / "templates" / lang)),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["tojson"] = json.dumps
    return env


def generate_python(ir: schema_ir.ProtocolIR) -> None:
    ctx = pyrender.render_context(ir)
    env = _env("python")
    PYTHON_OUT.mkdir(parents=True, exist_ok=True)
    (PYTHON_OUT / "__init__.py").write_text(
        '"""AUTO-GENERATED by protocol/codegen/generate.py — do not edit by hand."""\n'
    )
    (PYTHON_OUT / "models.py").write_text(env.get_template("models.py.jinja").render(ctx))
    (PYTHON_OUT / "methods.py").write_text(env.get_template("methods.py.jinja").render(ctx))
    print(f"wrote {PYTHON_OUT}/{{__init__,models,methods}}.py")


def _clang_format_inplace(paths: list[Path]) -> None:
    """Applies fronts/qt/_clang-format (see AGENTS.md) to generated C++ output
    so generated/ matches the same house style as hand-written code —
    clang-format finds it by walking up from each file's directory, same as
    it would for any other file under fronts/qt/."""
    clang_format = shutil.which("clang-format")
    if clang_format is None:
        print("warning: clang-format not found on PATH — generated C++ left unformatted", file=sys.stderr)
        return
    subprocess.run([clang_format, "-i", *[str(p) for p in paths]], check=True)


def generate_cpp(ir: schema_ir.ProtocolIR) -> None:
    ctx = cpprender.render_context(ir)
    env = _env("cpp")
    CPP_OUT.mkdir(parents=True, exist_ok=True)
    models_h = CPP_OUT / "Models.h"
    rpc_methods_h = CPP_OUT / "RpcMethods.h"
    rpc_methods_cpp = CPP_OUT / "RpcMethods.cpp"
    models_h.write_text(env.get_template("Models.h.jinja").render(ctx))
    rpc_methods_h.write_text(env.get_template("RpcMethods.h.jinja").render(ctx))
    rpc_methods_cpp.write_text(env.get_template("RpcMethods.cpp.jinja").render(ctx))
    _clang_format_inplace([models_h, rpc_methods_h, rpc_methods_cpp])
    print(f"wrote {CPP_OUT}/{{Models,RpcMethods}}.h, {CPP_OUT}/RpcMethods.cpp")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lang", nargs="+", choices=["python", "cpp"], required=True)
    args = parser.parse_args()

    ir = schema_ir.build()

    if "python" in args.lang:
        generate_python(ir)
    if "cpp" in args.lang:
        generate_cpp(ir)


if __name__ == "__main__":
    main()
